# Generated by Django 3.1.6 on 2021-02-17 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=30)),
                ('number', models.PositiveBigIntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
                ('joined_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
