# Generated by Django 3.1.6 on 2021-02-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_soup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answer_ratio',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='user',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='submission',
            field=models.IntegerField(default=0),
        ),
    ]
