# Generated by Django 3.1.6 on 2021-03-05 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_soup', '0002_auto_20210218_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='answer_ratio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='user',
            name='submission',
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
