# Generated by Django 3.1.6 on 2021-03-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_soup', '0004_user_baekjoon_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
