# Generated by Django 3.1.6 on 2021-03-07 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_soup', '0005_auto_20210305_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
    ]
