# Generated by Django 3.1.6 on 2021-03-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_soup', '0003_auto_20210305_1800'),
        ('Rank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chicken_soup.user'),
        ),
    ]
